project:
  type: book

book:
  title: "Working with research data"
  author: "Daniel Manrique-Castano"
  date: "2024-07-17"
  chapters:
    - index.qmd
    - intro.qmd
    - FileTypes.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: source

